const scoreRules = {
  1: {
    rolePerLevel: 100,
    equipPerLevel: 18,
    skillPerLevel: 7,
    beastPerLevel: 8,
    relicPerLevel: 33,
    baseLevel: 100,
    relicBase: 13,
    equipCount: 5,
    skillCount: 8,
    beastCount: 4,
    relicCount: 5,
    relicScale: 20,
    seasonBonusCore: 0,
  },
  2: {
    rolePerLevel: 100,
    equipPerLevel: 18,
    skillPerLevel: 7,
    beastPerLevel: 8,
    relicPerLevel: 33,
    baseLevel: 130,
    relicBase: 13,
    equipCount: 5,
    skillCount: 8,
    beastCount: 4,
    relicCount: 5,
    relicScale: 20,
    seasonBonusCore: 45,
  },
  3: {
    rolePerLevel: 100,
    equipPerLevel: 14,
    skillPerLevel: 5,
    beastPerLevel: 6,
    relicPerLevel: 26,
    baseLevel: 130,
    relicBase: 13,
    equipCount: 5,
    skillCount: 8,
    beastCount: 4,
    relicCount: 5,
    relicScale: 20,
    seasonBonusCore: 0,
  },
};
